
#
#   make - csps-demo
#

    csps-demo:directories
	gcc -o ../bin/csps-demo csps-demo.c -O3 ../bin/libcsps.a -lm

#
#   make - csps-time
#

    csps-time:directories
	gcc -o ../bin/csps-time csps-time.c -O3 ../bin/libcsps.a -lm

#
#   make - Directories
#

    directories:
	mkdir -p ../bin
